#pragma once

#include "KeyCodes.hpp"

#include <GLFW/glfw3.h>
#include <unordered_map>

namespace Fusion {

	const std::unordered_map<int32_t, EKeyCode> GLFWKeyMappings =
	{
		{ GLFW_KEY_SPACE, EKeyCode::Space },
		{ GLFW_KEY_APOSTROPHE, EKeyCode::Apostrophe },
		{ GLFW_KEY_COMMA, EKeyCode::Comma },
		{ GLFW_KEY_MINUS, EKeyCode::Minus },
		{ GLFW_KEY_PERIOD, EKeyCode::Period },
		{ GLFW_KEY_SLASH, EKeyCode::ForwardSlash },
		{ GLFW_KEY_0, EKeyCode::Alpha0 },
		{ GLFW_KEY_1, EKeyCode::Alpha1 },
		{ GLFW_KEY_2, EKeyCode::Alpha2 },
		{ GLFW_KEY_3, EKeyCode::Alpha3 },
		{ GLFW_KEY_4, EKeyCode::Alpha4 },
		{ GLFW_KEY_5, EKeyCode::Alpha5 },
		{ GLFW_KEY_6, EKeyCode::Alpha6 },
		{ GLFW_KEY_7, EKeyCode::Alpha7 },
		{ GLFW_KEY_8, EKeyCode::Alpha8 },
		{ GLFW_KEY_9, EKeyCode::Alpha9 },
		{ GLFW_KEY_SEMICOLON, EKeyCode::Semicolon },
		{ GLFW_KEY_EQUAL, EKeyCode::Equal },
		{ GLFW_KEY_A, EKeyCode::A },
		{ GLFW_KEY_B, EKeyCode::B },
		{ GLFW_KEY_C, EKeyCode::C },
		{ GLFW_KEY_D, EKeyCode::D },
		{ GLFW_KEY_E, EKeyCode::E },
		{ GLFW_KEY_F, EKeyCode::F },
		{ GLFW_KEY_G, EKeyCode::G },
		{ GLFW_KEY_H, EKeyCode::H },
		{ GLFW_KEY_I, EKeyCode::I },
		{ GLFW_KEY_J, EKeyCode::J },
		{ GLFW_KEY_K, EKeyCode::K },
		{ GLFW_KEY_L, EKeyCode::L },
		{ GLFW_KEY_M, EKeyCode::M },
		{ GLFW_KEY_N, EKeyCode::N },
		{ GLFW_KEY_O, EKeyCode::O },
		{ GLFW_KEY_P, EKeyCode::P },
		{ GLFW_KEY_Q, EKeyCode::Q },
		{ GLFW_KEY_R, EKeyCode::R },
		{ GLFW_KEY_S, EKeyCode::S },
		{ GLFW_KEY_T, EKeyCode::T },
		{ GLFW_KEY_U, EKeyCode::U },
		{ GLFW_KEY_V, EKeyCode::V },
		{ GLFW_KEY_W, EKeyCode::W },
		{ GLFW_KEY_X, EKeyCode::X },
		{ GLFW_KEY_Y, EKeyCode::Y },
		{ GLFW_KEY_Z, EKeyCode::Z },
		{ GLFW_KEY_LEFT_BRACKET, EKeyCode::LeftBracket },
		{ GLFW_KEY_BACKSLASH, EKeyCode::Backslash },
		{ GLFW_KEY_RIGHT_BRACKET, EKeyCode::RightBracket },
		{ GLFW_KEY_GRAVE_ACCENT, EKeyCode::GraveAccent },
		{ GLFW_KEY_WORLD_1, EKeyCode::World1 },
		{ GLFW_KEY_WORLD_2, EKeyCode::World2 },

		{ GLFW_KEY_ESCAPE, EKeyCode::Escape },
		{ GLFW_KEY_ENTER, EKeyCode::Enter },
		{ GLFW_KEY_TAB, EKeyCode::Tab },
		{ GLFW_KEY_BACKSPACE, EKeyCode::Backspace },
		{ GLFW_KEY_INSERT, EKeyCode::Insert },
		{ GLFW_KEY_DELETE, EKeyCode::Delete },
		{ GLFW_KEY_RIGHT, EKeyCode::RightArrow },
		{ GLFW_KEY_LEFT, EKeyCode::LeftArrow },
		{ GLFW_KEY_DOWN, EKeyCode::DownArrow },
		{ GLFW_KEY_UP, EKeyCode::UpArrow },
		{ GLFW_KEY_PAGE_UP, EKeyCode::PageUp },
		{ GLFW_KEY_PAGE_DOWN, EKeyCode::PageDown },
		{ GLFW_KEY_HOME, EKeyCode::Home },
		{ GLFW_KEY_END, EKeyCode::End },
		{ GLFW_KEY_CAPS_LOCK, EKeyCode::CapsLock },
		{ GLFW_KEY_SCROLL_LOCK, EKeyCode::ScrollLock },
		{ GLFW_KEY_NUM_LOCK, EKeyCode::NumLock },
		{ GLFW_KEY_PRINT_SCREEN, EKeyCode::PrintScreen },
		{ GLFW_KEY_PAUSE, EKeyCode::Pause },
		{ GLFW_KEY_F1, EKeyCode::F1 },
		{ GLFW_KEY_F2, EKeyCode::F2 },
		{ GLFW_KEY_F3, EKeyCode::F3 },
		{ GLFW_KEY_F4, EKeyCode::F4 },
		{ GLFW_KEY_F5, EKeyCode::F5 },
		{ GLFW_KEY_F6, EKeyCode::F6 },
		{ GLFW_KEY_F7, EKeyCode::F7 },
		{ GLFW_KEY_F8, EKeyCode::F8 },
		{ GLFW_KEY_F9, EKeyCode::F9 },
		{ GLFW_KEY_F10, EKeyCode::F10 },
		{ GLFW_KEY_F11, EKeyCode::F11 },
		{ GLFW_KEY_F12, EKeyCode::F12 },
		{ GLFW_KEY_F13, EKeyCode::F13 },
		{ GLFW_KEY_F14, EKeyCode::F14 },
		{ GLFW_KEY_F15, EKeyCode::F15 },
		{ GLFW_KEY_F16, EKeyCode::F16 },
		{ GLFW_KEY_F17, EKeyCode::F17 },
		{ GLFW_KEY_F18, EKeyCode::F18 },
		{ GLFW_KEY_F19, EKeyCode::F19 },
		{ GLFW_KEY_F20, EKeyCode::F20 },
		{ GLFW_KEY_F21, EKeyCode::F21 },
		{ GLFW_KEY_F22, EKeyCode::F22 },
		{ GLFW_KEY_F23, EKeyCode::F23 },
		{ GLFW_KEY_F24, EKeyCode::F24 },
		{ GLFW_KEY_F25, EKeyCode::F25 },
		{ GLFW_KEY_KP_0, EKeyCode::NumPad0 },
		{ GLFW_KEY_KP_1, EKeyCode::NumPad1 },
		{ GLFW_KEY_KP_2, EKeyCode::NumPad2 },
		{ GLFW_KEY_KP_3, EKeyCode::NumPad3 },
		{ GLFW_KEY_KP_4, EKeyCode::NumPad4 },
		{ GLFW_KEY_KP_5, EKeyCode::NumPad5 },
		{ GLFW_KEY_KP_6, EKeyCode::NumPad6 },
		{ GLFW_KEY_KP_7, EKeyCode::NumPad7 },
		{ GLFW_KEY_KP_8, EKeyCode::NumPad8 },
		{ GLFW_KEY_KP_9, EKeyCode::NumPad9 },
		{ GLFW_KEY_KP_DECIMAL, EKeyCode::NumPadDecimal },
		{ GLFW_KEY_KP_DIVIDE, EKeyCode::NumPadDivide },
		{ GLFW_KEY_KP_MULTIPLY, EKeyCode::NumPadMultiply },
		{ GLFW_KEY_KP_SUBTRACT, EKeyCode::NumPadSubtract },
		{ GLFW_KEY_KP_ADD, EKeyCode::NumPadAdd },
		{ GLFW_KEY_KP_ENTER, EKeyCode::NumPadEnter },
		{ GLFW_KEY_KP_EQUAL, EKeyCode::NumPadEqual },
		{ GLFW_KEY_LEFT_SHIFT, EKeyCode::LeftShift },
		{ GLFW_KEY_LEFT_CONTROL, EKeyCode::LeftControl },
		{ GLFW_KEY_LEFT_ALT, EKeyCode::LetAlt },
		{ GLFW_KEY_LEFT_SUPER, EKeyCode::LeftSuper },
		{ GLFW_KEY_RIGHT_SHIFT, EKeyCode::RightShift },
		{ GLFW_KEY_RIGHT_CONTROL, EKeyCode::RightControl },
		{ GLFW_KEY_RIGHT_ALT, EKeyCode::RightAlt },
		{ GLFW_KEY_RIGHT_SUPER, EKeyCode::RightSuper },
		{ GLFW_KEY_MENU, EKeyCode::Menu }
	};

}
